apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: todo-push-event-listener
spec:
  namespaceSelector: {}
  resources:
    kubernetesResource:
      replicas: 1
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push
    interceptors:
    - params:
      - name: secretRef
        value:
          secretName: github-credentials
          secretKey: webhook-secret
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && !body.ref.startsWith('refs/tags'))
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: build-from-push-todo
    template:
      ref: todo-trigger-template
  - bindings:
    - ref: github-push
    interceptors:
    - params:
      - name: secretRef
        value:
          secretName: github-credentials
          secretKey: webhook-secret
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/tags'))
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: build-from-tag-todo
    template:
      ref: todo-tag-trigger-template