apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: todo-tag-trigger-template
spec:
  params:
  - description: the specific commit SHA.
    name: git-revision
  - description: The commit message
    name: git-commit-message
  - description: The  name of the git repo
    name: git-repo-name
  - description: The git repository URL.
    name: git-repo-url
  - description: The repository name for this PullRequest.
    name: pusher-name
  - description: The content type of the webhook.
    name: content-type
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: todo-tag-pipeline-
    spec:
      pipelineRef:
        name: todo-tag-pipeline
      params:
        - name: SOURCE_CODE_GIT_REPO
          value: "$(tt.params.git-repo-url)"
        - name: SOURCE_CODE_GIT_REF
          value: develop
        - name: INFRA_GIT_REPO
          value: "https://github.com/secangkirkopipanas/todo-application-infra.git"
        - name: INFRA_GIT_REF
          value: develop
        - name: GIT_COMMIT_ID
          value: "$(tt.params.git-revision)"
      workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: todo-repo
        - name: maven-local-repo
          persistentVolumeClaim:
            claimName: maven-local-repo
