apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- target:
    kind: Deployment
    name: todo
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: bitnami/postgresql:15.4.0-debian-11-r54