apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-java-app
  namespace: todo-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: todo-java-app
          image: >-
            quay.io/rh_rh/todo-java:6be778a9e6
