---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
  namespace: todo-dev
spec:
  encryptedData:
    database-password: AgC5MXGcNlUYIfl/6xdKrBph2jutGpPohLWbTUZuZWNpmoml6kppN7rLo6UwKvsxA/icrjyufrD2H01UV7XXVwPj/mbyw1DUvN62Xnu9grLl7ZZ2a8Sh6nwmd2I+2Rns7dD9JEvNZKkRlLBC1J0ltHvfERgC+2s4UNtXdqazPgepAAf560AXj7Og+HKRmQLogQavFumU2NjrUcgX2UKiNZFreISi4per0B/5GuUYBvtBe2B1QZAJuXIEVp8LDC84dxKdjSRCfyFo2/+oc+Xya2/noGK8quTnBFHPUS9eclwrstxf92YO4Sx2npZJDSsWa/ADcqAcSadaYW2osmHwMjlpAQq5Ic3CF1lshoaOTf53sclwcVA8IMWHaFbhPSmY+s1hsHUtAHVK6YYo+gCz5vuqAFGLMDVS0ifgSPCCBwonuiu3XGy0+WG+mpFGed+HwU78wmCJP7MxTed2kQwAl9i8TjQIHFyZK3uR544kt5aMabX23E3bm0bHA6LMek4/rkr+KLQzqQIp1XZAVi89eq9WPkDwBf8pLUi4/uiKHJwIABCC+gvCQlPI7JN/rHnD53nUIA1ueJw7ydtenlEc7C9tlUTVCurKbU/R1qdaLGPCZOStb95hUJU7dg9m03IcULuqb5o/9MLGfNtwXJ4ciwIEtuvGTHvvoAScEyKP83AuRrkHgJ7p+O/wGAbE0RdI8nckCWefG3Ca42Nf
    database-user: AgCGIRwfoQ7Wma0maJsNJXaWPa3Q97DsmsoUnJM9EQ2vDNRRXQPUihlnvqtR6Vx10+v2GpKZAFvfPlYZREvYKhp1jlTpJN4pUl0BXJTB09/iM0ccOWO2+DfdWskDwyWWm8P6etToS7YRvhCDAYg7l7lghbxFxZ/SbwwZpJE+bMl8DHkqvLtEBR4W+4PBsRbRUefCx7q/gIzPrYc+q8AmNnsubl+s+irDA6WANnlAhdUUlX7+BeKXLX6axtt4KePb3ppwNFfd02VrGQ4qpGh2rCrkykgY65toN043oO3aZrS4Q/mi0zDtGg/6TPBayzCLaX8aKMpXUb0xFqAMXX/uLSrAL+W79JkkmsAbuzJMYbaX18nsBP9gsxKtFmz3IcB2vptBOqKjD/kOgNiRwvCyYYtKwtMhKhnrAmihDgnjqoqrGkUk/XLQhUq7bGOemJn6ZR8ex688M6MMEOEaDm1EuZIzL1AYGeORqJg7oYvJjnXrtqp+dCNmpOm4W4EjhABWyjt2oEZfG+5rOFTfYbKjNgA1+BdRfR5QV4X2omuvSRS9Ogb9rUd70lEftIqj5gYEjEd801Oi8C6kcouI6kmspAfpbeTjC6C3lj6mipsUWdr9EaHqEZ3rryYIFI+vA9BQnWooMdixPz1Rop776EEHfce2qj+h8vPxox5TZr4my30O6YeRJDEYE+eV6itz09ymOwj1MXF01Nj0
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-dev
    type: Opaque
