apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: todo-app
    app.kubernetes.io/name: todo
    app.openshift.io/runtime: spring
  name: todo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: todo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo
        app.kubernetes.io/part-of: todo-app
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms1G -Xms1G"
        - name: SPRING_ACTIVE_PROFILES
          value: dev
        - name: DATASOURCE_URL
          value: jdbc:h2:mem:todo
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: todo-database
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: todo-database
        - name: DATASOURCE_DRIVER_CLASSNAME
          value: org.hibernate.dialect.H2Dialect
        image: quay.io/rh_rh/todo-application:latest
        imagePullPolicy: IfNotPresent
        name: catalog
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: catalog-app
      serviceAccountName: catalog-app
      terminationGracePeriodSeconds: 30