apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-manifest
spec:
  params:
    - default: >-
        https://dev-user:openshift@gitea.apps.cluster-5khxf.5khxf.sandbox2563.opentlc.com/dev-user/securing-software-supply-chain.git
      name: gitRepositoryUrl
      type: string
    - default: main
      name: gitRepositoryRevision
      type: string
    - name: imageTagName
      type: string
    - default: 'true'
      name: verbose
      type: string
    - default: ''
      name: pushToRevision
      type: string
    - default: 'false'
      description: |
        When set to `"true"`, skip verifying the TLS certs of the Central
        endpoint.  Defaults to `"false"`.
      name: insecure-skip-tls-verify
      type: string
  steps:
  - image: 'quay.io/redhat-gpte/alpine-git:latest'
    name: update-manifest
    script: |
      #!/usr/bin/env sh

      printf -- "------------------------------\n"
      printf    " Update Manifest and Push     \n"
      printf -- "------------------------------\n\n"

      if [[ "$(params.verbose)" == "true" ]] ; then
        set -x
        echo "**** Cloning $(params.gitRepositoryUrl) into $(pwd)/repository"
      fi

      git clone "$(params.gitRepositoryUrl)" $(pwd)/repository
      cd $(pwd)/repository
      git checkout "$(params.gitRepositoryRevision)"

      curl -s -k -L \
        "https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64" \
        --output ./yq
      
      ./yq e -i '.spec.template.spec.containers[0].image = "quay.io/rh_rh/todo-application:$(params.imageTagName)"' deploy/app-java/base/dep-todo.yaml
      cat deploy/app-java/base/dep-todo.yaml

      #if [[ ! -z "$(params.pushToRevision)" ]]; then
      #  git add *
      #  git commit -m "Updated manifest"
      #  git push origin $(params.pushToRevision)
      #fi

    volumeMounts:
      - mountPath: /workspace/repository
        name: repository
    workingDir: /workspace
  volumes:
    - emptyDir: {}
      name: repository