---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: todo-tag-pipeline-run
  namespace: todo-app
spec:
  pipelineRef:
    name: todo-tag-pipeline
  params:
    - name: CONFIG_GIT_REPO
      value: "https://github.com/secangkirkopipanas/todo-application-config.git"
    - name: CONFIG_GIT_REF
      value: develop
    - name: APP_VERSION
      value: "0.0.1-SNAPSHOT"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: todo-repo
