---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: todo-pipeline-run
  namespace: todo-app
spec:
  pipelineRef:
    name: todo-pipeline
  params:
    - name: SOURCE_CODE_GIT_REPO
      value: "https://github.com/secangkirkopipanas/todo-application.git"
    - name: SOURCE_CODE_GIT_REF
      value: develop
    - name: CONFIG_GIT_REPO
      value: "https://github.com/secangkirkopipanas/todo-application-config.git"
    - name: CONFIG_GIT_REF
      value: develop
    - name: APP_VERSION
      value: "0.0.1-SNAPSHOT"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: todo-repo
    - name: maven-local-repo
      persistentVolumeClaim:
        claimName: maven-local-repo
