apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth-secret
  namespace: todo-app
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://secangkirkopipanas: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@github.com

---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
data:
  config.json: ewogICAgImF1dGhzIjogewogICAgICAgICJxdWF5LmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJjbWhmY21nNk1EZHhOR2xEZWtaaFRuSnlWemd3VkVsalpsRlpWVVZoZGxkU2JsZ3hRemhYUzNkUFowdGthMkYzVUdkNlUya3pPRWhVT0cxWU9YVmlRakJMYlN0NVZBPT0iLAogICAgICAgICAgICAiZW1haWwiOiAiIgogICAgICAgIH0KICAgIH0KfQ==