apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: dep-todo.yaml
  
configMapGenerator:
  - name: todo-configmap
    literals:
      - timezone="Asia/Singapore"
      - java_options="-Xms1G -Xmx1G"
      - spring_active_profiles="prod"
      - datasource_url="jdbc:postgresql://todo-java-db-svc:5432/todo-java-prod-db"
      - datasource_driver_classname="org.postgresql.Driver"
      - jpa_dialect="org.hibernate.dialect.PostgreSQLDialect"
