apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: dep-todo.yaml
  
configMapGenerator:
  - name: todo-configmap
    literals:
      - timezone="Asia/Singapore"
      - java_options="-Xms1G -Xms1G"
      - spring_active_profiles="dev"
      - datasource_url="jdbc:h2:mem:todo"
      - datasource_driver_classname="org.h2.Driver"
      - jpa_dialect="org.hibernate.dialect.H2Dialect"
