---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgA5gqdjQRBkpQDFMvU4ex92X1zA6WqJI4vdHGCuXwYMdpukdNtNjryxSP87+hq8gRkDMbtlmkRXVQxJpUCjpDX9F8Uq3zH33HgOdwH5LLyqEQ7mWDLb1WBF2A6BZxb5mfJKZqnssBBZHufopqpMJQoXpShvk27PADkjiPermgL4lLeD7ipryzH9j5jPHeg7b0kpVjHe1hBJZiqpHL8Vl1ICAzeXHeTh68KbAw7R+Caa239k90RdZp1jhWwfyYj3FtqdDww/xzc0iyUlkJL8jv2Kf/KIOQgSgUUkUC8pYrTGAwnnaNe8jRHUJrvweX2eYMog1O3ZK+vN92lHxOU1Yu/I6yK7NThrlqRTzgM1hNPcqF+SXlR5OTMfvXZoUvBQUd04Brqh8IpJFJL7YAA0Bm1FKjSYqqjQbe78MlONY2zYtD2PU1HK+humObqzhvwsHxD60FO04K5S3VszhJvxORSXcXZfoWKYdwnKu/hQ3e/8vde45P3S3tiYkQSrBAB7A0AO+385v3YWL0eYTLWeOyw8tlhoNEvecpQZFWUadQ5uMjlwUfgCy/K3g438EGL9pW1i/nFlGbZZ+0X0rVKf2IcwRiVtYqZi/COeqlHDrxAS0sksbBFkc8p3rorqR6HNNPT6AAPHPUW0b2o0lCdEM44IRnv7zJWj/t40YvcVaydn5oz+PliYJhvQB/wwBND9yQe2t6zUZ7PfbD61
    database-user: AgDK7B2B5bZCY5VkN+qZ0QeWq2JEjklXNaTCp/6mplmgpYipr9RCaIzThznI2TMcddFvZ4KTlHWejZMkZy/7xkE48qN/2xdGVo2k7YdnIki9os9+QghZQnHzXLLnxIb4BIw1ryXCOOPUiolfp410m9PwMu5FAnFp3ebqjY1VCl6ErayHCIUpHgYaD3NHTjaBDCwslC70ZP2WYfg3rD41HBrDaTKHqmSMOIXYK8t/0OPkZDBIFvKzGNQava679Y6YLjzZTprGOK3e6u3ZuawQPzmPzdmpFPaKYzg0caWdqkBPA4qjo2Ex06/VYNohX3Z1Wz4dbs20Vx82zcuOVV02PLxG+6McoQkfHh3x87eT3JaFBsJPv5W7qgOYji+YM3FzHlSB1CQTAtJLxZFnqXx7lN5YmfXxjxskDd5yGNSl5iFxAAGMdr3H9/bP2jwHSnzKY5TSwE9750r+7tt/XvbQLhYbYxwArkjJJARutlDl/g8yTwbZm3XQYpzhX2MI7ePbUZJTjetmaWtxUsbzpOEPW0qnUN1EuPtESP1eXBtiDe0r4uwEgP/1aDVQrE2q4KLFjtLeQfe2+6DWqiwf8ov3sallWVb4iYQV7wVdOFIzwOE4YpV8LOPLn7osRSC0DYYyiaI89CuTKon8aCRi4sIJNBG+NZG/6X8y7wBeh6AkiMv6sJ0+oMdZbhHU5MopCwBC9d/ghiEsPHLU
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
    type: Opaque
