---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgCyM25HnrXlRaOaH1+plR4uMRPgJBFlq35IP0ny9Dn4Fa6hyG1Cz6cP8H30lLGAh2DEkXi0rhhzAPDJGa4r6aOGHZBIKIQqLnGJZ/nWK34SS3xHC+YkizCknXuB7HzWY5c4BQ18mA0Jjt52XwDsBX5o5F14C/LJ9vOCpaEtczxE5CprYAAqjE1Ll1fn/Q1Sk9SCnxUx5ROw5ctNT2eMNz6o5Y69KWuA+/QQwu5xzB7X9pcwTGQaCUTB5rnva2hblSj4XEQSQUF7XiW1pa2KLFg16PSrgGl+sQa0qsfdaK1jHFG1injfH20OL6qlwt5opsGfqMU6lG54ydnfiisdF35UVzhtbzGVy0kL0owYB8BWffnQT3NhW2ghsme7JGDITVLmgWRmPXec7c1zFTjGiueVyeGvT7Bqisz1zZI31SnByZdpwiJT2V5BXS5x2A1DQoAE2PgsXSN1R4O+AE9UTfAp9Q3uI78lOcvyj69mGRJg9Nbv8lzf6i2L3jfGDQ2fH8GbBPLm9rptEgb9yA+WV5fXRAOcCfjhpPCXVAgv0pPXqBenJYTAUQALL2EhJFItmq+p5t6yxwn8YJRvHrTP0yirsqVSNE+HQs6PRRkkB9y+QBSEYCr2mblD3R7FamULPzS3VoIUoVabqnBPFlvv+OFxzBCmsroo+01pWCCElcdSMsLkcHU2nih1WnP23F8T8pjVZBtweF9uOykF
    database-user: AgA46TKbxXx0YxAGG1TlIJp+E9hwV4EPjNs6stIx/oFBFMiJxCJmfC9UInVjFVVI6aCvuJP+CodEzKZC7lvtE6jTgGDYs/1UyqNa694uL1dhcAulGdBBXWM8OMX6ZEYCxmLt8GS43pDXtfGZpdPlpCTRojlVepXEqDBGSDXd+OCMSkl+WuUE78YMfEpeNeVh2z/+CwnXRqfeadcjT/kn770AuDmndBFoGMjMS7yd9VENTtbJTCXsP/Ry65YY9HFg+e47Ls5nRu0HDIwC8BMhPhkEdiS39L4jGQZ1JWUK9/7Tx80JTBJby+S45iuaaEsS3d0foM4GMLPzjvcrI1lH+JfQL40NA+pBHRnNvqtM2zQfraOJZl+yiCcQbl+xrGkZ4QrBlPJYZt6xqGqKhx4pY3//GljXk1zxv0kr8bb23wipxUoW7w5OoUHAY7irLAp9qcuZXrYq8E0vD9CBuBL4v9wl+odiWqp88s4MQYKUvtAs90VoRvE4/5eOj4v7oNuRt8bcbcFa8SUYADAPzvAf4c4my4i2S7Awtl8jxB5j/3jiiSmiHPDxGBikqo0MY70hfZFN2Pdfz+xjuYKi7WwbUMIfSZwqWqMjCP/VXWEYZ6J6yvfqwTvLqxYgW+l9AulIgv7TRztMs7Ycf0VA7sv/tNZgVBjmdk7NriI1vh7gY96pUzgxrBgK+IZ8tzkliVt13Uc+w+a00/4w
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-prod
    type: Opaque
