---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: todo-tag-pipeline-run
spec:
  pipelineRef:
    name: todo-tag-pipeline
  params:
    - name: CONFIG_GIT_REPO
      value: "https://github.com/secangkirkopipanas/todo-application-infra.git"
    - name: CONFIG_GIT_REF
      value: develop
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: todo-repo
