apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: todo-tag-pipeline
spec:
  params:
    - name: INFRA_GIT_REPO
      type: string
      default: "https://github.com/secangkirkopipanas/todo-application-infra.git"
      description: "Git repository of infra code repo"
    - name: INFRA_GIT_REF
      type: string
      default: develop
      description: "Git ref of infra code repo"
  workspaces:
    - name: shared-workspace
      description: | 
        This workspace contains source code, so they can be read by the next task.
  tasks:
    - name: update-manifest
      taskRef:
        name: update-manifest
      params:
        - name: insecure-skip-tls-verify
          value: "true"
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)
        - name: pushToRevision
          value: "$(params.INFRA_GIT_REF)"
        - name: imageTagName
          value: "$(params.APP_VERSION)"
    - name: acs-deployment-check
      taskRef:
        name: acs-deployment-check
      runAfter:
        - update-manifest
      params:
        - name: rox_api_token
          value: stackrox
        - name: rox_central_endpoint
          value: stackrox
        - name: insecure-skip-tls-verify
          value: "true"
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)