apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: dep-todo-db.yaml

configMapGenerator:
  - name: todo-java-db-configmap
    literals:
      - timezone="Asia/Singapore"
      - database_name="todo-java-prod-db"