---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgDPsnNO/2x4nme+DXRFurpVO7FfLSD2Q3hU98neH/g1bt/mzfCVC9BRGYLDVhiHFEdizRXez7AZSjJoDrP+nPisaHrgLStlpellJMTBgeaCcJiNpqO++KTcKONsjsvqx4ZRHwIm3Z2gx/y0bo0lfeyZK/RlX4NoGfbr456pjTWic2ArWi/JXLA5JU7YQ5zNCtpr7LNhhPS4UHx0KTEp9OZ/U+hubD/ESbV7Mp3SIyz3td3MKiGXOH17DtCeFLm8DHsJ9SlgKheAyINuVlqwbYGR4xwhVI3xxPI54YVHrgNrNWYW2H/qHjihvsov0k5NIU4N3+Pp3FeDklAHuI2yGma0xvH+7+5b6apMtYky92/8PzIfAFlCKWyxUUtPrAqieiqdAa0/9EANtu1kng5TGZghprLGy7RL6BrX9Z8y2SH8a/mU3A/ZGVH7rcipMW3mo8Fo07AksU9ZYxmBy7lpqPZZBS7sPML6oH2JVhuJQdN2rb20BAlvYdCUOOXOkxK4iyTi8ZsQNVeUUcrXZG++wKWQGpIuyHaGdniq2DPHNuo4KONBDf+GsSiwv/nhsQJEtbm82zd0v7afuAZvq8IKVYAkml3QVHejHiqCFTbCV7LngBfbvJEUwWKaID3ov7GJftKOBsEohyUcQkKFzJMJ2vgpXw07bNA2xCG2MUs4Vh9RXB6FNtLxi6LM/iQp6okc6Fln0yMl4K6+IZZc
    database-user: AgAHI27Y94hH8ZDKgXamL8LX3zqFQQA/KQZ1ui+DIiQQPnzwPV3DN+ABPcX6fynnWknqiGT9+yxtfd2eqTYNxHdCLEpkpjqvs1pomKPYUTKIuOHbYqhuV4An9SUu4Nl9IgiKnR/icPK9fZh4jTOSqciy59HZgeNr9hRJvPIMdDMb9cobLyorKn6fKSJH9J9Ds7UeVkWCKLVVXqVqG4ss1aQc9cU+vM4FDf888vjuAkdNj8Awupi+UYGgTcSR3d1qdNeDnJNV9wK+w9gbx06VMU/YLLtYb/3l52Qs2MXPdRxww4F5v1cuhvKu8ZZtt/UBmLdCl+W5cAZDhlytU9jAVgHvp80QjMa9OqtM+C0HlyeruNDgssWs7bhlJ6aQeNe0Oe5EdAId7vmPHRSq97Bhh8DP9vEsQL0rnOZ42BEIqAaRfRULgjlYxtb4tYG6oaEykGeMKaaV0UXG3R8nYS+cIQoHg6QXQdtpWTXJ9lhAHBQFruymPycXtSuLmFJ8p69nguhhlNctpq9Y9j+FGGM/BnZ7t1Hmv/G7DKLuC0tq7q1jgo6yMKdn7xDIA6V7lx2oujB0ycJLoLzbz4BH6lEEXr+rSXrIKTYqb/vbXg9JTvEAPXqdR3S/3VaOscFl0qZCm+58sJK16gA0YsbmpTmfmRif5AMBxqPRnpz9gMv2McxRrGQJiiSHGgC+/OhmYsOw7svoR5+8Q6++
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-dev
    type: Opaque
