apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dotnet-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: todo-java-app
          image: >-
            quay.io/rh_rh/todo-java:53ecf3efd7
