---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgBCiSGBZkna0EJqEq0l2S1hByNO8eEk3Ldp3tUNRDVPUt5na89b8fC5asQimRdhZxdyOlz6hSpFkpy9mFkd8oSRQ70vao3TpgdJRDRvIRlmmJwKRRQrCkN2lucDE1W8RVnootMR2GHuIZfFjUe7wF8JRbEDfLtW68sesi97IFEJblp09Cc4OSeIdK/XM8TzMPtNvcgEsCLGt5QSkRLMHLwrF6Y4O97Gw3sweJ7lRfZA+ymNvLbApkeSSpZOusrdEv7M+OUTNbGnxzQEFkJIFslMJFvEt5bggO2FTQCOL1IZf7DxjWIDVifO51E45kURLQUuG3CIi2+jSivWfgVRtCXdHf9ggsOMaBvVK1gYNMn6FyueFr6jhkOYryHwRsYG3mcA5txS/xGkfqpAvy0MLOMIMUQnU6L6/FkcuuXAKxKG5uFjNSmHdOLCfuNO7bYNpoPDyQQ7ExU5autCuy2m/o8qmkuVwXhL6mA5opKA3Gy6JOQyXUoACRvEx2vp6FbDvYGdczbpQYgvsbImj2pBZgZOTJDj3WgZGfQQqA561V+vRJbrC/3WtMkGKE5CyoOGwJrAaEG0ua8HQKk3mNNx+E1c/FcsLOuxbR9ybnpTT1u1EHBFzdMo0MZLoUh7msdt7xYNK5pgfTXIoPYKTqm/zhHEdl+AANz2nipM/O8NWJLpBhlSZ7M1V+XRjO6aKGqTmUI/CjXExqgCMOLU
    database-user: AgDlSnzxsF3uIwV86YOun2qO+7hgwBkeYUMKTKUtnNihx3qZgCHB/bGKTTtAi44KTSr+Ikz0acUwo6m4lCqVlhPvB4W7xeIXEiXDH4rhbiB4HE0vVj/0yH/sRSFpnQ3/tcjQ9/PPKqfGdDsB4qVRXkhw7V1SnNsKyU2RjcWLKd/+MiZfMcM/fy+OxxvGxsdYDXCKFdYqWkq7tnily8JaA1MWWvYowM/DotSjyTNXXEdK61EErbzkdM1Ok406SNwwQCqzIyEf7CEYM8MlNq+DjYs2CCGiVf4P1KqfM5K/FjSMxDacgg6xGMmggd6YaHfo/0YxdNqayBcK/4sLmChT1u/6kYszfYZyX6RvLCET0LVgtvuLXh/bKtNnXxJr+cgJjbFqiwD7ZzNSQvUMnAmRWjZyQav6NGJbyMrbgEigitiqb/B8T98crtxncasO4yeZvXK0tTDsKeJ1RceJW2irfo/9YSCsLggOtARXMZvjYnDwOKGKebAD+ugwZvM447tvJRfY+BhQ1LZA2j61zl+eli8xBcTO5FnByEPp1VFXY2gIoZyef4zlRRaBc1I0lBVKQ/WhUOXjIkSk5FgyAVIGm1rgXkuBqD5uCNYdjXs8djXCeQvfnfdqKjLn5p04lTkEE3BAGmwwHt9vDYkIDIq6GhOyp3PfkIVCT6Yku07751LSoDbxQeMP6YjcyiunFiAZtcZV1Z5ugb0H
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-sit
    type: Opaque
