---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
  namespace: todo-sit
spec:
  encryptedData:
    database-password: AgCH4d2qaglAYwImRirRBKHr8EGYOX+sTepxE8kR45M11ys2eC/qJNb99lJQ/wPGiW0cR3qRakYHuhvE1ULg6t0ijZ2kHfzYYvGRzZQjmyU7N0WbcdrmOCE8H71aLIAUM0WekmZ0eeeQ3krtT7h4IO4k2iT4P/cL05AP72giH4GKUUX8RzJkj0jy1XOLrHRkB2Jejf4QVStUyEYxn2KEgb5siyC3G7fySUfv7koke9WbNdFLtf7BqbhaDyJfuJIn1j32kShtbgIyHK3a+fe0tCdM0KEHHbeMev33OAym8FGvet1fMiG2/42zSYw/HeqjzORUdterFNyK9/JnXXXj2eaOb1wpxWndRKSWHv4XX9bYjcn1qm5G+7h2Ck5LD0PIg8OrkjBc3quAAp3/1YlNuNA8b9y4upuG4Lp4TRGFpFbVL0y6KG65/vxDinShZo1hmP6sBu4UuYUe77DafDiqctuajceaQsiOVs1zOSvZfq4EFVFwytxUgha/zQ4DDpmtyYtCrCq5d7quZIZVrY/AVPjbJIC9xD7cHT/uOPZvewvz0aJ++GMg2uI5dTmga2XwslRpDt3wXXehwBKTG8LVGiVEwR1f5COhnGOzUkoGFwNRdN4husUHsxT5aEaybW/k59lc/YGw5+lKzv0CTVAwCm7TxJaoWtK2IZmLWMvapfOBgzln2sGTHdJyNVXlAJuU0lDV9iuuUDhrZ2OF
    database-user: AgCmVKeTt0FKDlUmcx7gyZ/7n/fZRePDQoyKr9nkCrcPft98A7vaIgXiibTsAVGEsDCbA2X48brGF/0qslky1+juRQDvK9+FjGwAI3G2ltxKqcZN8llLORt8Sc5oZTMzxnYUBoKDuqUVFIVnx/F+CV1lc8UNZSstidQli6sCwEPuAOn0E2exy8DEJ7GMmp6zwWCOZc1uIBMbBE7HbPwl+481HBEsqYz53QUGJm7yAm/NGLA3m/hkbAhs9y0hXE4hZvYWmvrb7eL/lNZUFTbmjQJ1JCqVWw9kixpO7y2SFvfJ0Vg57W82OsRqHfsPJZwLef1ibBoWqE7kQ85Ov25pFV5aWKOPdhHK0wcFqkZicSzq+FkGFQzH9ivvWQs1L3eGwXgD9oLzph1YXTHoOxL+gfk75SkUv5dXo7r/ZLrPe5PEMGD9TlS5yLPiwfrCNAO5Iw2J+TMz3AnCu0H2oIH7h4qnsorI+4OvP4/s65gKjgiXjMoSyvu4QVvhe8/s3JNgCGEO8eFLHHFzdzq9jZoSZsQZ2p5pAGK1MCyMYSy2NBZqy/S+DqCbeDyF0r9Km0YdrYRNrEYB6WyVGDMSVOU7fcgSkNtM7xnQRdjD4g3RuD7maqR3v5LvVZBMHXXMnCspXrjhWFG+TEpbpbqGAniVVdCSK/8gDG3dbkEx+Gah2tfY7g2fTllS9o4of5ZzF+BQYJomHSNTq5y9
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-sit
    type: Opaque
