---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgCCepqVDxqAl9SzqAZsUiuhmLjM7WwhwyzPS0R5WoWy0Ol91gM2FdTmcdVzQ0eIuuhQyNV3pPGwKme/ra82AatqUguuUymGCjgYB2LkckXAUFT4VbK07tG+T7PJxJWO1dw4Phb56AVgSCRj5CB7pjy8g0tCaSwzs8XQXWD9WB/25X8CEi+TyyxA/5waQ30vuRYQaO9rb0iEBxSrp60GRbOUCf9Gs3yxUmhKYjqfkmZJeWGXiygurGE39gSGwsNWZnwR0uLzJsp4IFOZNPkgfD1hyCwXhXX+zudwXz0fCw+6vUDbJeJuzGRccuGrbzt1wsvxKbzbytjkx105FDWUhqrilEghdH8HDx27VUlGsQXnxUAn8pP1TPwPc42d4bbRnmHwISMG5AsCo0srr9lSW2NExkps6RdcWP/eb6+mMcGvt7OGq/mTkP326e7RxGj9tz6whv9vculB7hZcGXoA/cLeGypjZ3xRrQQxKF1GuULJn4I66rvWSRktacdgKIKZONpUTLQvj1aqTj66wu/BGMzO7hSBFiv1wXJLJSmZB7Hq4z9a6HABVJ3WTEMsjWT9JEG4vMwHwBJkjcWbiKIUqMCmt6T9iEhe6MDw5RrWraNYF9hkGYrnP4YBh7bhMGtlS6725zE9vVHqtoqFTqclV8R8CGMdb1ZidNMEARVLrUNt7zXnwAEJ0gmdRl3IZiCdoSkrrRHxFNL6fn16
    database-user: AgDCqG7pJQLsOpcQOUPGm/G0bYWLG1bTEFPdab0FQ4Va0JSIT6qAThHdxFxHr5RPYdu5b0ZA14pTpbicm1e3l6cm//t1f5ZKWvMuPQr/NZdPV7MzRaqslqL4zaDtgM9v6TNmW8P/MCuI/PwPs1g2PL9eDTOHKP78XAUVvqUjlTBYpUL1+xwamYGz1jhJfeI+aZ1McDlNyFpwHcBFxdTTHAWKXFeGM8DoTv2VZCde1Rjq051awlXbaUg1iRsOBvbzPsTahVIWgkpSugG4BuPm17R4uNTp8RffeqO3RrpTGipqYB9Z9yKY3PfCdXGLXI5Z5Sy2dkUamFhdx3yc17yqY0EXBqARc5JBhgj1P+EjlLPPc+ffiHchKRsTydyE5fJSNSCdvAWVcSAgPDb6bBmBmMSZwkcN+HDd39MRwOpIqCUVd8Xjjh68a7QmFulnK6zwCASZ2R0MYfPEkiHzKKH/OijdIeAX9asP0OBi5wXr8gL1Epmr4zKcD9bKcG1V7NndmT5PQNCPg2tDiaeBmHHAIm8U6ClrKB3kCnKotCemO5zmaEe7WXD4DcE74CdbJGe7sCqrkzhhovhR/KcSLSNXgL1Y4jjDKQY8jPud5nUPPNalHHOTa3ktQ0I3wzKxBSlyZX7szPF+9karWB8m3t/f1t3guO/yDqCP2cGpgvmuFlFG0G5+qDKP1TViveAJBsarBADZwbzRKEb3
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-sit
    type: Opaque
