---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
spec:
  encryptedData:
    database-password: AgCWWISm5uxAawx8Lh3LVY3CWCm5zwLYfwyFNyNtIwyUDg3IWAGhcPrnLgsWVgB6uprO2eW1hhsnqTzhgfs3GqcLfXxaE38rTstUW3vFdhN78cRKe2bWHww7kWeaFYJZtOSt5bn2mYFSG4omhRPzjp34TIEc+H8cmvqpXQY6eWUAh1i+R7iurwYbm1pF+meApi4yyzzNwfKs7vkGJi6fmsDYlr02X9svEeM/2rhxVU9Dx1/hmfkdViucAFIl+9gfdOU+giVGqWeuKUEX7BH2zHh/fYhZZv24/vE+xWp7vbC21w7QbF60Cosnv4x+jIWWTuo6yJmzqEEf0uGQzuvRq4yH22fL/LpQGCKocp0cIZ9XHPOdK0/to1hRL4TNk+yBmmWDpcUoB85VK43MnSo5du+tuuiE582D7U70zLtGZRt9kbR//B8Dhawq0fZqzgkENAB/0raU698yOkTFfKC90l0RsoFBE/shJm0+PSCQJ7UiL5rXggjuR9y32LDeV6OkcZfh/IPxKi+vzaaOCDYNJpac8OzJHgreyLz3KMBCF43fjdHQfaQYFegUO22PhJp6vPOH37Cup0KKkJ6YzJH2vZ2rqMMXfGa9q+b2jn5Z2Lf3jY2Th5RL9aWjuNW6ORpNbI3Aj1XE7oEZ5K7nBHuSwmKGneeWwVg8TTt+6V5flJRbdQEKfliHHQXG5VejzFPB+TJyC/0XhZ485oo8
    database-user: AgBD6AFX4f1Y1SnPOm+uJv5oggmD8f0nPA6+qlQ72/0uX0mS1IeuqjCxF+oqfBUeuD0Tro6DfNCq+AoDbx1ChfHQUAP1jcwckPzlkAlaLOVerh1P587uOG7IGlw86jhpsa3uMao1enoNtgs+CB8DV9rPyoNaosln0XVF/yfD/rZ602a+k3z7qLTGoud6YO47EcOVX67YSz9Fb3/CjRRm0Feo+Xo+kxLLCUHaBzeBh9kUwpyBLDrobWtBF09iUtd+f0ryc4FtHEioLQVcU3HcsyXaAAl04W3/TrPv90X6pbsIIrLNtvcUiYRL4/fje2iugPbhV8gSvR72zilnNd4HDZsFUl4iAN06wzNlC22KLyaY3l/duG9+1W0PAuEfompyP+wWDqGfQq9Ee7R1xBaGUqoWPn6Sk3jdfCdWFrvEBX+4NXQOq8TzIfY4q1FPSgYPPEgIi5NU3ksAC59a7TVNv7HkfUzFAr36utpfPNpEcqp79ylYv8rjySuTGxAbFA4VAuQz2Hg5SFKtthRo+z4aPVkoMFZXQXkWUkwI4ZkZjwxtjA6kz37Y/UU9XVbs+v6lZaBJ7uSCl9AbGmui0ChxuSrwA4awtw8bsBBloh3OFaBkruZPMR97EQRAvSh6p2n20A6DVxdbdSzNeIGQASw72Z+cOpyMpmUlsapa/cvygL6oCD/KknRWYy/Zu5etPFnpG10rb+7QFIu4
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
    type: Opaque
